export const CREATE_CHART = { CREATE_CHART : 'CREATE_CHART' };
export const CREATE_SAMPLE = { CREATE_SAMPLE : 'CREATE_SAMPLE' };
export const REMOVE_SAMPLE = { REMOVE_SAMPLE : 'REMOVE_SAMPLE' };
export const CHANGE_SAMPLE = { CHANGE_SAMPLE : 'CHANGE_SAMPLE', CHANGE_DATA : 'CHANGE_DATA' };
